### ISSUE TITLE
[DsfrInput] FontSize et margin-top

### ISSUE THREAD

**Issue by gideruette** [dnum-mi/vue-dsfr#173]
Dans le DsfrInput, la fontSize est à 0.8em tandis que sur leDsfrSelect elle est à 1rem. De plus, il manque un margin-top de 0.5rem, ce qui brise l'alignement des champs (voir image).

Il semble que ce style a été ajouté en surcharge dans le composant, y-a-t-il une raison particulière à cela ?

![image](https://user-images.githubusercontent.com/15626856/145093786-49632f02-8996-46d3-9eb7-b979f5bb5640.png)

```css
.fr-label {
  font-size: 0.8rem;
  display: block;
  color: var(--g800);

.fr-input {
  margin: 0;
  border: 0;
}
```
