### ISSUE TITLE
[DsfrBreadcrumb] Ne s'affiche pas sur grand écran

### ISSUE THREAD

**Issue by gideruette** [dnum-mi/vue-dsfr#302]
Etant donné la propriété `hideButton: false` dans les data, et la classe css 
```css
@media (min-width:48em) {
 .fr-breadcrumb__button {
  display:none
 }
```
Sur grand écran le bouton ne s'affiche pas, et le fil d'Arianne non plus

Le problème avait disparu, mais il est à nouveau présent.

Je suggère d'ajouter une propriété permettant d'initialiser la propriété `hideButton`
